// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of OrbitCapture NAM — see LICENSE.

// Package jobs holds the daemon's domain types: job kinds, lanes, states, the
// closed vocabularies of the shared schema (0001_init.sql: job_kind, job_state,
// job_error, stop_state, live_error), and the Job row. It depends on nothing else
// in the tree so the store and the worker share one definition of a Job.
package jobs

import "time"

// Kinds (the job_kind domain). train_more continues a succeeded train from the
// checkpoint the app snapshotted into job_resume when it queued the row.
const (
	KindTrain     = "train"
	KindTrainMore = "train_more"
	KindProbeSelf = "probe_self"
)

// Lanes (jobs.lane, generated by the schema): train and train_more share the
// GPU-bound train lane; probe_self drains in its own lane alongside it.
const (
	LaneTrain = "train"
	LaneProbe = "probe"
)

// States (the job_state domain).
const (
	StateQueued    = "queued"
	StateRunning   = "running"
	StateSucceeded = "succeeded"
	StateFailed    = "failed"
	StateCancelled = "cancelled"
)

// Verdicts for probe_self (jobs.verdict).
const (
	VerdictPass = "pass"
	VerdictFail = "fail"
)

// Error codes — the job_error domain, a CLOSED list the app branches on. Nothing
// outside this list may ever be written to jobs.error_code.
const (
	ErrTrainFailed     = "train_failed"
	ErrResumeFailed    = "resume_failed"
	ErrStalled         = "stalled"
	ErrNoVerdict       = "no_verdict"
	ErrNoESR           = "no_esr"
	ErrStopFailed      = "stop_failed"
	ErrScratch         = "scratch"
	ErrSpawn           = "spawn"
	ErrMaterialize     = "materialize"
	ErrWavInvalid      = "wav_invalid"
	ErrTakeGone        = "take_gone"
	ErrSignalMismatch  = "signal_mismatch"
	ErrBaseUnavailable = "base_unavailable"
	ErrSchemaMismatch  = "schema_mismatch"
	ErrCancelled       = "cancelled"
)

// Stop states (the stop_state domain) — the daemon's answer channel to
// jobs.stop_requested_at: pending (acknowledged, no whole checkpoint pair yet),
// armed (a pair exists, the trainer is being killed), refused (the harvest found
// nothing usable → the job failed stop_failed, or the job is a probe), done (the
// job succeeded).
const (
	StopPending = "pending"
	StopArmed   = "armed"
	StopRefused = "refused"
	StopDone    = "done"
)

// Live errors (jobs.live_error) — why a live_requested_at could not be answered
// with a job_snapshots row.
const (
	LiveNoCheckpoint = "no_checkpoint"
	LiveNotRunning   = "not_running"
	LiveTransient    = "transient"
)

// ProbeSelfEpochs is the fixed epoch count of a probe_self (the schema CHECKs it).
const ProbeSelfEpochs = 1

// Lane reports the scheduling lane a kind drains in — the same rule as the
// schema's generated jobs.lane column.
func Lane(kind string) string {
	if kind == KindProbeSelf {
		return LaneProbe
	}
	return LaneTrain
}

// LaneKinds returns every kind that drains in lane.
func LaneKinds(lane string) []string {
	if lane == LaneProbe {
		return []string{KindProbeSelf}
	}
	return []string{KindTrain, KindTrainMore}
}

// ValidKind reports whether k is one of the known job kinds.
func ValidKind(k string) bool {
	switch k {
	case KindTrain, KindTrainMore, KindProbeSelf:
		return true
	}
	return false
}

// IsTerminal reports whether a state is final (no further transitions).
func IsTerminal(state string) bool {
	return state == StateSucceeded || state == StateFailed || state == StateCancelled
}

// StoresModel reports whether a kind produces a .nam (a job_result row). Probes never do.
func StoresModel(kind string) bool { return kind == KindTrain || kind == KindTrainMore }

// Job is a row of the shared jobs table as the daemon reads it. Nullable columns
// are pointers. The request block (take_id … queued_at) is the app's and is frozen
// once the row is claimed; the run block is what this daemon writes.
type Job struct {
	ID int64

	// ---- the app writes (the request) ----
	TakeID             int64   // 0 = the take was wiped; the journal row survives, the claim skips it
	TakeLabel          string
	Kind               string
	Lane               string
	Epochs             int // total target (train_more: the TOTAL, not the delta)
	Arch               string
	Priority           string // high | normal | low
	Latency            *int64 // latency_samples; NULL ⇒ the trainer auto-detects
	WavSHA             string // = take_audio.sha256: the bytes the job pins
	RequiredNamVersion string
	BaseJobID          *int64 // train_more: provenance (the checkpoint itself is in job_resume)
	StartEpoch         *int64 // train_more: where this run's numbering begins (app-written)
	ContinuesModel     bool
	AutostopExempt     bool
	StopRequestedAt    *time.Time
	StopReason         *string
	CancelRequestedAt  *time.Time
	LiveRequestedAt    *time.Time
	QueuedAt           time.Time

	// ---- the daemon writes (the run) ----
	State          string
	Worker         *string
	WorkerInstance *string
	ClaimToken     string // uuid text; "" until claimed. EVERY later write is fenced on it.
	PGID           *int
	ClaimedAt      *time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
	Epoch          *int64 // progress: last finished epoch (absolute)
	Reached        *int64 // epochs the weights HAVE at the end
	SPerEpoch      *float64
	ESR            *float64
	Verdict        *string
	ErrorCode      *string
	ErrorMessage   *string
	StopSeenAt     *time.Time
	StopState      *string
	LiveServedAt   *time.Time
	LiveError      *string
	NamVersion     *string
	DriverSHA256   *string
	SignalSHA256   *string
}
